### ISSUE TITLE
The source URL should not be hardcoded 

### ISSUE THREAD

**Issue by albancrommer** [inkle/inklewriter-to-ink#1]
**Type**
This is a bug request.

**What is the problem?**
The old URL for inklewriter is hardcoded in the following file

https://github.com/inkle/inklewriter-to-ink/blob/master/inklewriter-convert.ts#L484

**What would you expect**
I would like to pass more arbitrary variables to that function.

For example a complete URL with protocol + host + query

To do so, I would change the 2nd argument of the function into an `option` object, which would contain for now
```
  terminateAllLooseEnds : boolean
  storyURL : string
```

**Comment by joethephish** [comment]
Have simply removed the URL from the ink output (f62fcfd51d3391ba8ad4c7192778451d9f6769b7) since it's not necessarily exactly known (e.g. could've been transferred between inklewriter instances), and not that important.
